# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 485d25c86045a81d6a117602964169d94c0686fd26981fe5162fdef3b506329376e9bfeb6a6c60fa08b6a42fea322fe40d456a00ad2fbda52a3aab0b648a60f1

test:
  secret_key_base: eee340fa4ed12bb71babaa7e014811acef74c4d2b991d524deb5239bcb8d0b3d8626114bae80600be6282c9bbd359e1e53bd1bdeff5081295ea0ac7b024d9564

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
